---
title: "Hi"
date: 2018-12-13
---

title: Software Testing Foundation
author: Nguyen Trang
email: trangndt@talent.ominext.com
description: > # this means to ignore newlines until "baseurl:"
  hihihi

# social links
github_username:  trang-compsi

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

